//Jo
//@version=5
indicator("Liquidity Marker", overlay=true)


Show_label_01   = input.bool(true, 'Show level 01', group = "Settings")
Show_label_02   = input.bool(true, 'Show level 02', group = "Settings")
ler             = input.int(defval=0, title='Extend right', group = "Settings")
shift           = ler * 1000000
textSizeI       = input.string('Tiny', 'Text Size', ['Small', 'Tiny', 'Normal'], group = "Settings")
textSize        = textSizeI =='Small'? size.small : textSizeI =='Tiny'? size.tiny : size.normal 
textCol         = input.color(#fcfdfd9a, 'Text Color', group = "Color")


price01 = input.price(100, inline="Custom Main Anchor", confirm=true)
time01  = input.time(timestamp("2022-02-20"), inline="Custom Main Anchor", confirm=true)

liq_1_lab = Show_label_01 ? label.new(time+shift,price01,'X  $' + str.tostring(price01,format.mintick),textcolor=textCol, xloc = xloc.bar_time, color=color.new(color.black,100),  style=label.style_label_left, size=textSize) :na
label.delete(liq_1_lab[1])

price02 = input.price(100, inline="Custom Main Anchor2", confirm=true)
time02  = input.time(timestamp("2022-02-20"), inline="Custom Main Anchor2", confirm=true)

liq_2_lab = Show_label_02 ? label.new(time+shift,price02,'X  $' + str.tostring(price02,format.mintick),textcolor=textCol, xloc = xloc.bar_time, color=color.new(color.black,100),  style=label.style_label_left, size=textSize) :na
label.delete(liq_2_lab[1])