inp_text_size        = input.string("Tiny", options = ["Tiny", "Small","Normal"], title = "Text Sizs", group = "Settings")
TextSize             = inp_text_size == "Tiny" ? size.tiny : inp_text_size == "Small" ? size.small : inp_text_size == "Normal" ? size.normal : na
_txc                 = input.color(color.new(#404867, 0)   ,'Color', group = "Color")
i_show               = input.bool(true,     title='Show label', group = "Settings")

new_period(p) => p and na(p[1])
sm = time(timeframe.period, "0000-0000:2")
var float c = close

if new_period(sm)
    c := close   
if sm
    c := close
    
hide_col = time == sm ? color.new(color.green,100): _txc
plot(c, title="Close", linewidth=1, style=plot.style_linebr, color=hide_col)
label = i_show ? label.new(bar_index, c,   text="MONDAY CLOSE |  $"+ str.tostring(c, format.mintick),style = label.style_label_left, textcolor=_txc, size=TextSize, color= color.new(color.green,100)):na
label.delete(label[1])