//@version=5
indicator("Meme",shorttitle="Meme", overlay=true)

line_slope             = input.string("Sloped", options = ["Vertical", "Horizontal","Sloped"], title = "Line angle", group = "TL")
inp_line_stylez        = input.string("Solid", options = ["Dotted", "Solid", "Dashed"], title = "Zone Line Style", group = "TL")
Line_stz               = inp_line_stylez == "Solid" ? line.style_solid : inp_line_stylez == "Dotted" ? line.style_dotted : inp_line_stylez == "Dashed" ? line.style_dashed : na
zone_on_off            = true
inp_line_stylee        = input.string("Right", options = ["None", "Right"], title = "Line extend", group = "TL")
Line_ste               = inp_line_stylee == "Right" ? extend.right : inp_line_stylee == "None" ? extend.none : na
spacingz               = 80
AllColor3               = input.color(color.new(#fffefe, 50), "Zone Line Color", group = "Color")

priceA                 = 20181.83631254967
timeA                  = timestamp("2023-02-07T10:00:00")

priceB                 = 20466.179173497698
timeB                  = timestamp("2023-02-10T08:00:00")

priceC                 = 20915.62434080265
timeC                  = timestamp("2023-02-07T08:40:00")

priceD                 = 21264.173654222817
timeD                  = timestamp("2023-02-10T08:00:00")

sloping_hori_vert      = line_slope == "Horizontal" ? priceA :  line_slope == "Sloped" ? priceB : priceA 
hori_z                 = line_slope == "Vertical" ? timeA : timeB
hori_zb                = line_slope == "Vertical" ? extend.both : Line_ste

sloping_hori_vertb      = line_slope == "Horizontal" ? priceC :  line_slope == "Sloped" ? priceD : priceC 
hori_zv                 = line_slope == "Vertical" ? timeC : timeD
hori_zbb                = line_slope == "Vertical" ? extend.both : Line_ste

if barstate.islast
    secondsPerBar=time[0]-time[1]    

    zone_01    = zone_on_off ? line.new(timeA,priceA+spacingz,hori_z,sloping_hori_vert+spacingz, xloc = xloc.bar_time,color=AllColor3,style=Line_stz, extend = hori_zb):na

    zone_02    = zone_on_off ? line.new(timeA,priceA-spacingz,hori_z,sloping_hori_vert-spacingz, xloc = xloc.bar_time,color=AllColor3,style=Line_stz, extend = hori_zb):na

    zone_01a    = zone_on_off ? line.new(timeC,priceC+spacingz,hori_zv,sloping_hori_vertb+spacingz, xloc = xloc.bar_time,color=AllColor3,style=Line_stz, extend = hori_zb):na

    zone_02a    = zone_on_off ? line.new(timeC,priceC-spacingz,hori_zv,sloping_hori_vertb-spacingz, xloc = xloc.bar_time,color=AllColor3,style=Line_stz, extend = hori_zb):na