// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Jo-Pippin

//@version=5
indicator("Yearly Anchored Lines for 240M and 1D", overlay = true, max_bars_back = 500)

inp_text_size              = input.string("Tiny", options = ["Tiny", "Small","Normal"], title = "Text Sizs", group = "Global Settings")
TextSize                   = inp_text_size == "Tiny" ? size.tiny : inp_text_size == "Small" ? size.small : inp_text_size == "Normal" ? size.normal : na
inp_line_style             = input.string("Dotted", options = ["Dotted", "Solid", "Dashed"], title = "Line Style", group = "Global Settings")
Line_st                    = inp_line_style == "Solid" ? line.style_solid : inp_line_style == "Dotted" ? line.style_dotted : inp_line_style == "Dashed" ? line.style_dashed : na
Label_text_col             = input.color(color.new(#fdfdfd, 0), 'Label Text Color', group = "Global Settings")
Label_backg_col            = input.color(color.new(#565c70, 0), 'Label Background Color', group = "Global Settings")
Ext_line_col               = input.color(color.new(#afcff7, 35), 'Extend line color', group = "Global Settings")
open_col                   = input.color(color.new(#f74242, 100), 'Label Text Color', group = "Global Settings")

dot_thickness              = input.int(defval=4, title="Dot width", minval=1, maxval=30, step=1, group = "Global Settings")
dot_hight                  = input.int(defval=90, title="Dot hight", minval=1, maxval=130, step=1, group = "Global Settings")
dot_col                    = input.color(color.new(#f9f9fa, 0), 'Dot color', group = "Global Settings")
show_weekly_dots           = input.bool(true, 'Show dots', group = "Global Settings")
show_anchor_label          = input.bool(true, 'Show Main Anchor Label', group = "Global Settings")

show_Yearly_H_line         = input.bool(true, 'Show Yearly High Anchored Line', group = "Yearly Lines")
show_Yearly_L_line         = input.bool(true, 'Show Yearly Low Anchored Line',  group = "Yearly Lines")
show_Yearly_labels         = input.bool(false, 'Show Yearly Labels',  group = "Yearly Lines")
Yearly_HL_line_color       = input.color(color.new(#afcff7, 0), 'Yearly HL anchored line color',  group = "Yearly Lines")

show_Quarterly_H_line      = input.bool(true, 'Show Quarterly High Anchored Line', group = "Quarterly Lines")
show_Quarterly_L_line      = input.bool(true, 'Show Quarterly Low Anchored Line',  group = "Quarterly Lines")
show_Quarterly_labels      = input.bool(false, 'Show Quarterly Labels',  group = "Quarterly Lines")
Quarterly_HL_line_color    = input.color(color.new(#afcff7, 0), 'Quarterly HL anchored line color',  group = "Quarterly Lines")

show_Monthly_H_line        = input.bool(true, 'Show Monthly High Anchored Line', group = "Monthly Lines")
show_Monthly_L_line        = input.bool(true, 'Show Monthly Low Anchored Line',  group = "Monthly Lines")
show_Monthly_labels        = input.bool(false, 'Show Monthly Labels',  group = "Monthly Lines")
Monthly_HL_line_color      = input.color(color.new(#afcff7, 0), 'Monthly HL anchored line color', group = "Monthly Lines")

var ath = 0.0
var ath_bar = int(na)
if high > ath
    ath := high
    ath_bar := bar_index
    ath_bar

all_time_high_bar = ath_bar
ath_price = ath

//Time to bars
ts = timestamp("GMT+2", 2021, 01, 01, 00, 00, 00)
bartime = int(ta.change(time))
bars = math.floor((timenow - ts) / bartime)

//Yearly Elements
[open_y,open_py]   = request.security(syminfo.tickerid,"12M" , [open,open[1]], lookahead= barmerge.lookahead_off)
yearly_open_bar                 = ta.barssince(ta.change(time("12M")))
yearly_low_bar                  = ta.barssince(ta.pivotlow(yearly_open_bar,0))
yearly_high_bar                 = ta.barssince(ta.pivothigh(yearly_open_bar,0))

//Monthly Elements
[open_m]           = request.security(syminfo.tickerid,"M" , [open], lookahead= barmerge.lookahead_off)
monthly_open_bar                = ta.barssince(ta.change(time("M")))
monthly_high_bar                = ta.barssince(ta.pivothigh(monthly_open_bar,0))
monthly_low_bar                 = ta.barssince(ta.pivotlow(monthly_open_bar,0))

//Quarterly Elements
[open_q]           = request.security(syminfo.tickerid,"3M" , [open], lookahead= barmerge.lookahead_off)
quarterly_open_bar              = ta.barssince(ta.change(time("3M")))
quarterly_high_bar              = ta.barssince(ta.pivothigh(quarterly_open_bar,0))
quarterly_low_bar               = ta.barssince(ta.pivotlow(quarterly_open_bar,0))

//Yearly Elements re
//yearly lowest
lowest = low
for i = 1 to yearly_open_bar+1
	if (low[i]<lowest)
    	lowest := low[i]

//yearly highest
highest = high
for i = 1 to yearly_open_bar+1
	if (high[i]>highest)
    	highest := high[i]        

atl_bar = yearly_low_bar
all_time_low_bar = yearly_low_bar
atl_price = lowest   

prev_yearly_open_bar = bars
low_y  = lowest
high_y = highest

//Monthly Elements re
//Monthly lowest
lowest_m = low
for i = 1 to monthly_open_bar+1
	if (low[i]<lowest_m)
    	lowest_m := low[i]

//Monthly highest
highest_m = high
for i = 1 to monthly_open_bar+1
	if (high[i]>highest_m)
    	highest_m := high[i]        

low_m  = lowest_m
high_m = highest_m


//Quarterly Elements re
//Quarterly lowest
lowest_q = low
for i = 1 to quarterly_open_bar+1
	if (low[i]<lowest_q)
    	lowest_q := low[i]

//Quarterly highest
highest_q = high
for i = 1 to quarterly_open_bar+1
	if (high[i]>highest_q)
    	highest_q := high[i]        

low_q  = lowest_q
high_q = highest_q

choose_ath_orYearly_open        = input.string("ATH", options = ["ATH","ATL", "Yearly Open","Previous Yearly Open"], title = "Choose Source", group = "Global Settings")
ATH_yOpen                       = choose_ath_orYearly_open == "ATH" ? ath : choose_ath_orYearly_open == "ATL" ? lowest : choose_ath_orYearly_open == "Yearly Open" ? open_y : choose_ath_orYearly_open == "Previous Yearly Open" ? open_py : na
ATH_yOpen_text                  = choose_ath_orYearly_open == "ATH" ? "ath" : choose_ath_orYearly_open == "ATL" ? "atl" : choose_ath_orYearly_open == "Yearly Open" ? "yo" : choose_ath_orYearly_open == "Previous Yearly Open" ? "pyo" : na
ATH_yOpen_bar                   = choose_ath_orYearly_open == "ATH" ? ath_bar : choose_ath_orYearly_open == "ATL" ? bar_index[yearly_low_bar] : choose_ath_orYearly_open == "Yearly Open" ? bar_index[yearly_open_bar] : choose_ath_orYearly_open == "Previous Yearly Open" ? bar_index[prev_yearly_open_bar] : na

show_m240_mD_mW =timeframe.period == "180" or timeframe.period == "240" or timeframe.period == "300" or timeframe.period == "360" or timeframe.period == "420" or timeframe.period == "480" or timeframe.period == "540" or timeframe.period == "600" or timeframe.period == "660" or timeframe.period == "720" or timeframe.period == "D" or timeframe.period == "W" ? true :false

//Monthly Elements
yearly_open_to_monthly_high_anchored_line_extend = show_Monthly_H_line and show_m240_mD_mW ? line.new(ATH_yOpen_bar,ATH_yOpen, bar_index[monthly_high_bar], high_m, extend=extend.right, color=Ext_line_col, style=line.style_dotted, width=1):na
line.delete(yearly_open_to_monthly_high_anchored_line_extend[1])
yearly_open_to_monthly_low_anchored_line_extend  = show_Monthly_L_line and show_m240_mD_mW? line.new(ATH_yOpen_bar,ATH_yOpen, bar_index[monthly_low_bar],  low_m, extend=extend.right, color=Ext_line_col, style=line.style_dotted, width=1):na
line.delete(yearly_open_to_monthly_low_anchored_line_extend[1])

monthly_high_label = show_Monthly_labels and show_m240_mD_mW? label.new(bar_index[monthly_high_bar], high_m, color=Label_backg_col, style=label.style_label_down,size=TextSize,text="mh",textcolor=Label_text_col ):na
label.delete(monthly_high_label[1])
monthly_low_label = show_Monthly_labels and show_m240_mD_mW? label.new(bar_index[monthly_low_bar], low_m, color=Label_backg_col, style=label.style_label_up,size=TextSize,text="ml",textcolor=Label_text_col ):na
label.delete(monthly_low_label[1])

monthly_high_low  = show_weekly_dots and show_m240_mD_mW ? line.new(bar_index[monthly_high_bar],high_m-dot_hight, bar_index[monthly_high_bar],  high_m+dot_hight, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(monthly_high_low[1])
monthly_dot_low  = show_weekly_dots and show_m240_mD_mW ? line.new(bar_index[monthly_low_bar],low_m-dot_hight, bar_index[monthly_low_bar],  low_m+dot_hight, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(monthly_dot_low[1])

//Quarterly Elements
yearly_open_to_quarterly_high_anchored_line_extend = show_Quarterly_H_line and show_m240_mD_mW? line.new(ATH_yOpen_bar,ATH_yOpen, bar_index[quarterly_high_bar], high_q, extend=extend.right, color=Ext_line_col, style=line.style_dotted, width=1):na
line.delete(yearly_open_to_quarterly_high_anchored_line_extend[1])
yearly_open_to_quarterly_low_anchored_line_extend  = show_Quarterly_L_line and show_m240_mD_mW? line.new(ATH_yOpen_bar,ATH_yOpen, bar_index[quarterly_low_bar],  low_q, extend=extend.right, color=Ext_line_col, style=line.style_dotted, width=1):na
line.delete(yearly_open_to_quarterly_low_anchored_line_extend[1])

quarterly_high_label = show_Quarterly_labels and show_m240_mD_mW? label.new(bar_index[quarterly_high_bar], high_q, color=Label_backg_col, style=label.style_label_down,size=TextSize,text="qh",textcolor=Label_text_col ):na
label.delete(quarterly_high_label[1])
quarterly_low_label = show_Quarterly_labels and show_m240_mD_mW? label.new(bar_index[quarterly_low_bar], low_q, color=Label_backg_col, style=label.style_label_up,size=TextSize,text="ql",textcolor=Label_text_col ):na
label.delete(quarterly_low_label[1])

quarterly_high_low  = show_weekly_dots and show_m240_mD_mW ? line.new(bar_index[quarterly_high_bar],high_q-dot_hight, bar_index[quarterly_high_bar],  high_q+dot_hight, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(quarterly_high_low[1])
quarterly_dot_low  = show_weekly_dots and show_m240_mD_mW ? line.new(bar_index[quarterly_low_bar],low_q-dot_hight, bar_index[quarterly_low_bar],  low_q+dot_hight, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(quarterly_dot_low[1])

//Yearly Elements
yearly_open_label = show_anchor_label and show_m240_mD_mW ? label.new(ATH_yOpen_bar, ATH_yOpen, color=open_col , style=label.style_label_down,size=TextSize,text=ATH_yOpen_text,textcolor=Label_text_col ):na
label.delete(yearly_open_label[1])

yearly_open_to_yearly_high_anchored_line_extend = show_Yearly_H_line and show_m240_mD_mW? line.new(ATH_yOpen_bar,ATH_yOpen, bar_index[yearly_high_bar], high_y, extend=extend.right, color=Ext_line_col, style=line.style_dotted, width=1):na
line.delete(yearly_open_to_yearly_high_anchored_line_extend[1])
yearly_open_to_yearly_low_anchored_line_extend  = show_Yearly_L_line and show_m240_mD_mW? line.new(ATH_yOpen_bar,ATH_yOpen, bar_index[yearly_low_bar],  low_y, extend=extend.right, color=Ext_line_col, style=line.style_dotted, width=1):na
line.delete(yearly_open_to_yearly_low_anchored_line_extend[1])

yearly_high_label = show_Yearly_labels and show_m240_mD_mW? label.new(bar_index[yearly_high_bar], high_y, color=Label_backg_col, style=label.style_label_down,size=TextSize,text="yh",textcolor=Label_text_col ):na
label.delete(yearly_high_label[1])
yearly_low_label = show_Yearly_labels and show_m240_mD_mW? label.new(bar_index[yearly_low_bar], low_y, color=Label_backg_col, style=label.style_label_up,size=TextSize,text="yl",textcolor=Label_text_col ):na
label.delete(yearly_low_label[1])

yearly_high_low  = show_weekly_dots and show_m240_mD_mW ? line.new(bar_index[yearly_high_bar],high_y-dot_hight, bar_index[yearly_high_bar],  high_y+dot_hight, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(yearly_high_low[1])
yearly_dot_low  = show_weekly_dots and show_m240_mD_mW ? line.new(bar_index[yearly_low_bar],low_y-dot_hight, bar_index[yearly_low_bar],  low_y+dot_hight, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(yearly_dot_low[1])