//Jo
//@version=5
indicator("Golden Pocket Marker", overlay=true, max_bars_back = 500)

Show_labels     = input.bool(true, 'Show labels', group = "Settings")
Show_RR         = input.bool(true, 'Show Golden Pocket Label', group = "Settings")
Show_GP_lines   = input.bool(true, 'Show Golden Pocket Lines', group = "Settings")

ler             = input.int(defval=80, title='Line extend right', group = "Settings")
textSizeIp      = input.string('Tiny', 'Price label size', ['Small', 'Tiny', 'Normal'], group = "Settings")
price           = textSizeIp =='Small'? size.small : textSizeIp =='Tiny'? size.tiny : size.normal 
textSizerr      = input.string('Tiny', 'Golden Pocket Label', ['Small', 'Tiny', 'Normal', 'Large'], group = "Settings")
rr_size         = textSizerr =='Small'? size.small : textSizerr =='Tiny'? size.tiny : textSizerr =='Normal'? size.normal : textSizerr =='Large'? size.large :na
line_style      = input.string(line.style_dotted, title="Line Style", options=[line.style_dotted, line.style_solid, line.style_dashed], group = "Settings")

dec             = input.int(2, title = "Decimal Points"   , minval=1, maxval =3)
textCol         = input.color(#080808, 'Text Color', group = "Color")
line_c          = input.color(#080808, 'Line Color', group = "Color")

show_660       = input.bool(true, '0.660',  confirm=true , group = "GP")
show_618       = input.bool(true, '0.618', confirm=true ,  group = "GP")

price_660      = input.price(0, '0.660'   ,      confirm=true, group = "GP")
price_618      = input.price(0, '0.618'   ,      confirm=true, group = "GP")

date1           = input.time(0,title ='Start Date',confirm=true,group='Elements')
date2           = input.time(0,title ='Input Candle Date',confirm=true,group='Elements')
bartime         = int(ta.change(time))
bars            = (math.floor((timenow - date1) / bartime))-1
bars2           = (math.floor((timenow - date2) / bartime))-1

//Decimals
d =  dec  == 1 ? "#.#"   : 
     dec  == 2 ? "#.##"  : 
     dec  == 3 ? "#.###" : na

Label_660 = Show_labels and show_660  ? label.new(bar_index[bars+1]+ler,price_660,"0.660 | " + str.tostring(price_660,d),textcolor=textCol, color=color.new(color.black,100),  style=label.style_label_left, size=price) :na
label.delete(Label_660[1])
Zero_660_line  = Show_GP_lines ? line.new (bar_index[bars2]+100,price_660, bar_index[bars+1]+ler, price_660  , color=line_c, style=line_style, width=1):na
line.delete(Zero_660_line[1])

Label_618 = Show_labels and show_618  ? label.new(bar_index[bars+1]+ler,price_618, "0.618 | " + str.tostring(price_618, d),textcolor=textCol, color=color.new(color.black,100),  style=label.style_label_left, size=price) :na
label.delete(Label_618[1])
Zero_618_line  = Show_GP_lines ? line.new (bar_index[bars2]+100,price_618, bar_index[bars+1]+ler, price_618  , color=line_c, style=line_style, width=1):na
line.delete(Zero_618_line[1])

Label_GP = Show_RR  ? label.new(bar_index[bars+1]+ler-2,(price_660+price_618)/2, "GOLDEN POCKET" ,textcolor=textCol, color=color.new(color.black,100),  style=label.style_label_left, size=rr_size) :na
label.delete(Label_GP[1])