//Jo-Pippin 
//@version=5
indicator(title='Quarterly Open Dots', shorttitle='Quarterly Open Dots', overlay=true , max_bars_back = 500)


i_open_c      = input.color(color.new(#f7f7f7, 0),  'Open Dots color', group = "Color Settings")
i_open_c2      = input.color(color.new(#f7f7f7, 62),  'First Day of the Quarterly Opening Range', group = "Color Settings")

[yo,yc1]      = request.security(syminfo.tickerid, '3M', expression=[open, close[1]], lookahead=barmerge.lookahead_on)
new_day       = yc1[1]  != yc1

plotchar(new_day ? yo : na, title='Close', char='☉', location=location.absolute, color=i_open_c, offset=0, size=size.tiny)

//Session Rules
bartimeSess = time('3M')
newbarSess = bartimeSess != bartimeSess[1]


high_range = ta.valuewhen(newbarSess, high, 0)
low_range = ta.valuewhen(newbarSess, low, 0)

//Calcul For Opening Range
locHigh = request.security(syminfo.tickerid, 'D', high_range)
locLow = request.security(syminfo.tickerid, 'D', low_range)
range_1 = locHigh - locLow

//Plot Statements For Initial Balance
plot1 = plot(time(timeframe.period) > 0 ? locHigh : na, title='IB High', color=color.new(#40596d, 100), linewidth=2)
plot2 = plot(time(timeframe.period) > 0 ? locLow : na, title='IB Low', color=color.new(#2195f3, 100), linewidth=2)

fill(plot1, plot2, i_open_c2)