// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Jo-Pippin

//@version=5
indicator("Quarterly Anchored for the 60M, 120M and 240M", overlay = true, max_bars_back = 500)

inp_text_size              = input.string("Tiny", options = ["Tiny", "Small","Normal"], title = "Text Sizs", group = "Global Settings")
TextSize                   = inp_text_size == "Tiny" ? size.tiny : inp_text_size == "Small" ? size.small : inp_text_size == "Normal" ? size.normal : na
inp_line_style             = input.string("Dotted", options = ["Dotted", "Solid", "Dashed"], title = "Line Style", group = "Global Settings")
Line_st                    = inp_line_style == "Solid" ? line.style_solid : inp_line_style == "Dotted" ? line.style_dotted : inp_line_style == "Dashed" ? line.style_dashed : na
Label_text_col             = input.color(color.new(#fdfdfd, 0), 'Label Text Color', group = "Global Settings")
Label_backg_col            = input.color(color.new(#565c70, 0), 'Label Background Color', group = "Global Settings")
Ext_line_col               = input.color(color.new(#afcff7, 35), 'Extend line color', group = "Global Settings")
open_col                   = input.color(color.new(#f74242, 0), 'Label Text Color', group = "Global Settings")

dot_thickness              = input.int(defval=4, title="Dot size", minval=1, maxval=10, step=1, group = "Global Settings")
dot_col                    = input.color(color.new(#f9f9fa, 0), 'Dot color', group = "Global Settings")
show_weekly_dots           = input.bool(true, 'Show dots', group = "Global Settings")

show_quarterly_H_line      = input.bool(true, 'Show quarterly High Anchored Line', group = "quarterly Lines")
show_quarterly_L_line      = input.bool(true, 'Show quarterly Low Anchored Line',  group = "quarterly Lines")
show_quarterly_labels      = input.bool(false, 'Show quarterly Labels',  group = "quarterly Lines")
quarterly_HL_line_color    = input.color(color.new(#afcff7, 0), 'quarterly HL anchored line color',  group = "quarterly Lines")

show_weekly_H_line         = input.bool(true, 'Show weekly High Anchored Line', group = "weekly Lines")
show_weekly_L_line         = input.bool(true, 'Show weekly Low Anchored Line',  group = "weekly Lines")
show_weekly_labels         = input.bool(false, 'Show weekly Labels',  group = "weekly Lines")
weekly_HL_line_color       = input.color(color.new(#afcff7, 0), 'weekly HL anchored line color',  group = "weekly Lines")

show_Monthly_H_line        = input.bool(true, 'Show Monthly High Anchored Line', group = "Monthly Lines")
show_Monthly_L_line        = input.bool(true, 'Show Monthly Low Anchored Line',  group = "Monthly Lines")
show_Monthly_labels        = input.bool(false, 'Show Monthly Labels',  group = "Monthly Lines")
Monthly_HL_line_color      = input.color(color.new(#afcff7, 0), 'Monthly HL anchored line color', group = "Monthly Lines")

//quarterly Elements
[open_q]     = request.security(syminfo.tickerid,"3M" , [open], lookahead= barmerge.lookahead_off)
quarterly_open_bar        = ta.barssince(ta.change(time("3M")))
quarterly_high_bar        = ta.barssince(ta.pivothigh(quarterly_open_bar,0))
quarterly_low_bar         = ta.barssince(ta.pivotlow(quarterly_open_bar,0))

//Monthly Elements
[open_m]     = request.security(syminfo.tickerid,"M" , [open], lookahead= barmerge.lookahead_off)
monthly_open_bar          = ta.barssince(ta.change(time("M")))
monthly_high_bar          = ta.barssince(ta.pivothigh(monthly_open_bar,0))
monthly_low_bar           = ta.barssince(ta.pivotlow(monthly_open_bar,0))

//weekly Elements
[open_w]   = request.security(syminfo.tickerid,"W" , [open], lookahead= barmerge.lookahead_off)
weekly_open_bar         = ta.barssince(ta.change(time("W")))
weekly_high_bar         = ta.barssince(ta.pivothigh(weekly_open_bar,0))
weekly_low_bar          = ta.barssince(ta.pivotlow(weekly_open_bar,0))


show_m15_m20_m30 = timeframe.period == "60" or timeframe.period == "120" or timeframe.period == "240" ? true :false

//Quarterly Elements re
//Quarterly lowest
lowest_q = low
for i = 1 to quarterly_open_bar+1
	if (low[i]<lowest_q)
    	lowest_q := low[i]

//Quarterly highest
highest_q = high
for i = 1 to quarterly_open_bar+1
	if (high[i]>highest_q)
    	highest_q := high[i]        

low_q  = lowest_q
high_q = highest_q

//Monthly Elements re
//Monthly lowest
lowest_m = low
for i = 1 to monthly_open_bar+1
	if (low[i]<lowest_m)
    	lowest_m := low[i]

//Monthly highest
highest_m = high
for i = 1 to monthly_open_bar+1
	if (high[i]>highest_m)
    	highest_m := high[i]        

low_m  = lowest_m
high_m = highest_m

//Weekly Elements re
//Weekly lowest
lowest_w = low
for i = 1 to weekly_open_bar+1
	if (low[i]<lowest_w)
    	lowest_w := low[i]

//Weekly highest
highest_w = high
for i = 1 to weekly_open_bar+1
	if (high[i]>highest_w)
    	highest_w := high[i]        

low_w  = lowest_w
high_w = highest_w

//Monthly Elements
quarterly_open_to_monthly_high_anchored_line_extend = show_Monthly_H_line ? line.new(bar_index[quarterly_open_bar],open_q, bar_index[monthly_high_bar], high_m, extend=extend.right, color=Ext_line_col, style=Line_st, width=1):na
line.delete(quarterly_open_to_monthly_high_anchored_line_extend[1])
quarterly_open_to_monthly_low_anchored_line_extend  = show_Monthly_L_line ? line.new(bar_index[quarterly_open_bar],open_q, bar_index[monthly_low_bar],  low_m, extend=extend.right, color=Ext_line_col, style=Line_st, width=1):na
line.delete(quarterly_open_to_monthly_low_anchored_line_extend[1])
monthly_high_label = show_Monthly_labels ? label.new(bar_index[monthly_high_bar], high_m, color=Label_backg_col, style=label.style_label_down,size=TextSize,text="mh",textcolor=Label_text_col ):na
label.delete(monthly_high_label[1])
monthly_low_label = show_Monthly_labels ? label.new(bar_index[monthly_low_bar], low_m, color=Label_backg_col, style=label.style_label_up,size=TextSize,text="ml",textcolor=Label_text_col ):na
label.delete(monthly_low_label[1])

monthly_high_low  = show_weekly_dots and show_m15_m20_m30 ? line.new(bar_index[monthly_high_bar],high_m-4, bar_index[monthly_high_bar],  high_m+4, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(monthly_high_low[1])
monthly_dot_low  = show_weekly_dots and show_m15_m20_m30 ? line.new(bar_index[monthly_low_bar],low_m-4, bar_index[monthly_low_bar],  low_m+4, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(monthly_dot_low[1])

//weekly Elements
quarterly_open_to_weekly_high_anchored_line_extend = show_weekly_H_line ? line.new(bar_index[quarterly_open_bar],open_q, bar_index[weekly_high_bar], high_w, extend=extend.right, color=Ext_line_col, style=Line_st, width=1):na
line.delete(quarterly_open_to_weekly_high_anchored_line_extend[1])
quarterly_open_to_weekly_low_anchored_line_extend  = show_weekly_L_line ? line.new(bar_index[quarterly_open_bar],open_q, bar_index[weekly_low_bar],  low_w, extend=extend.right, color=Ext_line_col, style=Line_st, width=1):na
line.delete(quarterly_open_to_weekly_low_anchored_line_extend[1])
weekly_high_label = show_weekly_labels ? label.new(bar_index[weekly_high_bar], high_w, color=Label_backg_col, style=label.style_label_down,size=TextSize,text="wh",textcolor=Label_text_col ):na
label.delete(weekly_high_label[1])
weekly_low_label = show_weekly_labels ? label.new(bar_index[weekly_low_bar], low_w, color=Label_backg_col, style=label.style_label_up,size=TextSize,text="wl",textcolor=Label_text_col ):na
label.delete(weekly_low_label[1])

weekly_high_low  = show_weekly_dots and show_m15_m20_m30 ? line.new(bar_index[weekly_high_bar],high_w-4, bar_index[weekly_high_bar],  high_w+4, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(weekly_high_low[1])
weekly_dot_low  = show_weekly_dots and show_m15_m20_m30 ? line.new(bar_index[weekly_low_bar],low_w-4, bar_index[weekly_low_bar],  low_w+4, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(weekly_dot_low[1])

//quarterly Elements
quarterly_open_label = show_quarterly_labels and show_m15_m20_m30 ? label.new(bar_index[quarterly_open_bar], open_q, color=open_col , style=label.style_label_down,size=TextSize,text="qo",textcolor=Label_text_col ):na
label.delete(quarterly_open_label[1])
quarterly_open_to_quarterly_high_anchored_line_extend = show_quarterly_H_line ? line.new(bar_index[quarterly_open_bar],open_q, bar_index[quarterly_high_bar], high_q, extend=extend.right, color=Ext_line_col, style=Line_st, width=1):na
line.delete(quarterly_open_to_quarterly_high_anchored_line_extend[1])
quarterly_open_to_quarterly_low_anchored_line_extend  = show_quarterly_L_line ? line.new(bar_index[quarterly_open_bar],open_q, bar_index[quarterly_low_bar],  low_q, extend=extend.right, color=Ext_line_col, style=Line_st, width=1):na
line.delete(quarterly_open_to_quarterly_low_anchored_line_extend[1])
quarterly_high_label = show_quarterly_labels ? label.new(bar_index[quarterly_high_bar], high_q, color=Label_backg_col, style=label.style_label_down,size=TextSize,text="qh",textcolor=Label_text_col ):na
label.delete(quarterly_high_label[1])
quarterly_low_label = show_quarterly_labels ? label.new(bar_index[quarterly_low_bar], low_q, color=Label_backg_col, style=label.style_label_up,size=TextSize,text="ql",textcolor=Label_text_col ):na
label.delete(quarterly_low_label[1])

quarterly_high_low  = show_weekly_dots and show_m15_m20_m30 ? line.new(bar_index[quarterly_high_bar],high_q-10, bar_index[quarterly_high_bar],  high_q+10, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(quarterly_high_low[1])
quarterly_dot_low  = show_weekly_dots and show_m15_m20_m30 ? line.new(bar_index[quarterly_low_bar],low_q-10, bar_index[quarterly_low_bar],  low_q+10, extend=extend.none, color=dot_col, style=line.style_solid, width=dot_thickness):na
line.delete(quarterly_dot_low[1])