//@version=5

indicator(title='Volume Candle Indicator', max_bars_back=2000, format=format.volume, overlay=true)


//------------------------------------------------------------------------------
// Inputs


length = input.int(300, title='MA Length', minval=2)
slength = input.int(300, title='Std Length', minval=2)
cmode = input.string('Heatmap', 'Color Mode', options=['Heatmap', 'Up/Down'])
zmode = input.string('Backgrounds', 'Display Heatmap Zones as', options=['None', 'Lines', 'Backgrounds', 'Both'])
bcolor_enabled = input(true, 'Colored bars')
osc = false

thresholdExtraHigh = input.float(5, title='Extra High Volume Threshold')

length := length > bar_index + 1 ? bar_index + 1 : length
slength := slength > bar_index + 1 ? bar_index + 1 : slength


pstdev(Series, Period) =>
    mean = math.sum(Series, Period) / Period
    summation = 0.0
    for i = 0 to Period - 1 by 1
        sampleMinusMean = nz(Series[i]) - mean
        summation += sampleMinusMean * sampleMinusMean
        summation
    return_1 = math.sqrt(summation / Period)
    return_1


mean = ta.sma(volume, length)
std = pstdev(volume, slength)
stdbar = (volume - mean) / std
dir = close > open
v = osc ? volume - mean : volume
mosc = osc ? 0 : mean

zshow_lines = zmode == 'Lines' or zmode == 'Both'
zshow_backgrounds = zmode == 'Backgrounds' or zmode == 'Both'

tst = ta.highest(v, math.min(300, bar_index + 1)) * 9999
ts0 = osc ? ta.lowest(v, math.min(300, bar_index + 1)) * 9999 : 0
ts1 = std * thresholdExtraHigh + mosc

conditionExtraHigh = stdbar > thresholdExtraHigh

//========//
LOW = 0.0
LOW := na(LOW[1]) ? na : LOW[1]
HIGH = 0.0
HIGH := na(HIGH[1]) ? na : HIGH[1]
//========//
//Stoploss

if conditionExtraHigh  //or conditionHigh
    LOW := low
    HIGH := high
    HIGH


s1 = plot(LOW, color=color.new(color.white, 60), style=plot.style_stepline)
tp1 = plot(HIGH, color=color.new(color.white, 60), style=plot.style_stepline)


alertcondition(conditionExtraHigh and high > HIGH, title='Entry-High Broken', message='High of the Volume Candle is Broken,Potential Entry')
alertcondition(low < LOW, title='Stoploss-Low Broken', message='Low of the Volume Candle is broken,Potential Stoploss')