//Jo-Pippin 
//@version=5
indicator(title='Yearly Open Dots', shorttitle='Yearly Open Dots', overlay=true , max_bars_back = 500)


yearly_dots_col              = input.color(color.new(#f7f7f7, 0),   'Open Dots color', group = "Color Settings")
yearly_opening_range_col     = input.color(color.new(#f7f7f7, 82),  'First Day of Year Opening Range color', group = "Color Settings")
line_col                     = input.color(color.new(#f7f7f7, 40),  'Latest yearly first day H L line color', group = "Color Settings")
[yo,yc1]                     = request.security(syminfo.tickerid, '12M', expression=[open, close[1]], lookahead=barmerge.lookahead_on)
new_day                      = yc1[1]  != yc1

plotchar(new_day ? yo : na, title='Close', char='☉', location=location.absolute, color=yearly_dots_col, offset=0, size=size.tiny)

//Session Rules
bartimeSess    = time('12M')
newbarSess     = bartimeSess != bartimeSess[1]
year_bars_back = ta.barssince(ta.change(time("12M")))
high_range     = ta.valuewhen(newbarSess, high, 0)
low_range      = ta.valuewhen(newbarSess, low, 0)

//Calcul For Opening Range
locHigh = request.security(syminfo.tickerid, 'D', high_range)
locLow  = request.security(syminfo.tickerid, 'D', low_range)
range_1 = locHigh - locLow

//Plot Statements For Initial Balance
plot1 = plot(time(timeframe.period) > 0 ? locHigh : na, title='IB High', color=color.new(#40596d, 100), linewidth=2)
plot2 = plot(time(timeframe.period) > 0 ? locLow  : na, title='IB Low',  color=color.new(#2195f3, 100), linewidth=2)

fill(plot1, plot2, yearly_opening_range_col)

show_bottom_or_top_line  = close[1] < locLow  ? true :false
show_bottom_or_top_line2 = close[1] > locHigh ? true :false

first_day_of_year_high_line = show_bottom_or_top_line2 ? line.new(bar_index[year_bars_back],locHigh,bar_index,locHigh,extend=extend.right,width=1,color=line_col):na
line.delete(first_day_of_year_high_line[1])

first_day_of_year_low_line = show_bottom_or_top_line ? line.new(bar_index[year_bars_back],locLow,bar_index,locLow,extend=extend.right,width=1,color=line_col):na
line.delete(first_day_of_year_low_line[1])

line1 = line.new(bar_index[1],locHigh,bar_index,locHigh,extend=extend.right,width=1,color=color.new(color.white,100))
line.delete(line1[1])
line2 = line.new(bar_index[1],locLow,bar_index,locLow,extend=extend.right,width=1,color=color.new(color.white,100))
line.delete(line2[1])

linefill3 = linefill.new(line1, line2, color = yearly_opening_range_col)

condition = ta.cross(close, locLow) or ta.cross(close, locHigh)
alertcondition(condition, title='Price crossed over the H or L of the first yearly day', message='Price crossed over the H or L of the first yearly day')

label_direction = close[1] > yo ? locHigh : locLow

test=label.new(bar_index+200,label_direction,text="Alert Line", size=size.tiny,color=color.white,textcolor = color.black)
label.delete(test[1])